### PR TITLE
Many more string translations (not all yet)

### PR DESCRIPTION
**Pull request by artus70**

### CODE REVIEW

**Comment by temasek** [comment]
Pls rebase your commits

**Comment by artus70** [comment]
Pls rebase your commits

Don’t understand - what does this mean exactly? What do I have to do now to get the translations imported into the branch?

Thanks and regards,
Volker

**Comment by temasek** [comment]
Your commit conflicts with current sources. Check your commit again.

**Comment by dischinator** [comment]
@artus70 you have to clone your repo locally then merge temaseks cm-12.1 branch into your patch branch to resolve some conflicts, will be easy probably just double translated strings. Or if you can't get it working I can merge it for you.

**Comment by artus70** [comment]
I’d be glad if you could help me with this. Can’t afford the time at the moment to do that local actions … So please take it and use it – thank you!

Von: André Perrot [mailto:notifications@github.com]
Gesendet: Dienstag, 3. November 2015 11:09
An: temasek/android_packages_apps_Settings
Cc: Volker Burggräf
Betreff: Re: [android_packages_apps_Settings] Many more string translations (not all yet) (#345)

@artus70https://github.com/artus70 you have to clone your repo locally then merge temaseks cm-12.1 branch into your patch branch to resolve some conflicts, will be easy probably just double translated strings. Or if you can't get it working I can merge it for you.

**Pull request closed without merging**
