### PR TITLE
German translations

### PR DESCRIPTION
**Pull request by dischinator**
Hi @temasek  I started working on german translations. So far I haven't done a lot, I open this pull request to check if I am doing right so far since I haven't done a lot work on the android tree so far.
Just post in comments if there's anything wrong and I will rework it.

Cheers
André

### CODE REVIEW

**Comment by temasek** [comment]
I did a glance and looks good. You want me to merge or you want to finish first?

**Comment by dischinator** [comment]
Up to you. Finishing complete will take me a while. So you could take this as a start and I will open another one later on.

**Comment by dischinator** [comment]
Also what I couldn't test is what happens if german translations are too long (german translations are infamous to be very long, makes writing on twitter in german no fun xD). So I hope this will not break layouts. I tried my best to keep them as short as possible.

**Comment by ghost** [comment]
Dischinator, good translations :+1:

I could help you with translation?

**Comment by dischinator** [comment]
@Trafalgar-Square thanks :-)
Sure help would be awesome. I digged down from top and am at line ~600 now so feel free to start translating from the bottom to top. And you find any typo, error or improvement in my translations either fix it or notify me.

**Pull request merged**
