### PR TITLE
Strings Updated PT-BR

### PR DESCRIPTION
**Pull request by Candiba**
Manual update of Brazilian Portuguese with Temasek features

### CODE REVIEW

**Comment by temasek** [comment]
temasek custom strings in res/values-pt-rBR/cr_strings.xml

**Comment by Candiba** [comment]
I did upload the full **strings.xml** in Brazilian Portuguese.
And the right would be only the translation of **cr_strings.xml**?
I'm sorry for the mess

**Comment by temasek** [comment]
strings.xml is aosp strings which we do NOT touch.
cm_strings.xml is cm strings which we try not to touch if possible
cr_strings.xml is temasek add-on strings which we translate from .../res/values/cr_strings.xml

**Comment by Candiba** [comment]
OK!
I will translate the file .../res/values/**cr_strings.xml**
Thanks for the info :)

**Pull request closed without merging**
