### PR TITLE
Update Italian translation

### PR DESCRIPTION
**Pull request by entony80**
other fixes

### CODE REVIEW

**Comment by SlimShadys** [comment]
Please merge this.

**Comment by entony80** [comment]
I'm sorry but I do not know how to merge it, I do not find any buttons for casting. you can do it

**Comment by SlimShadys** [comment]
I can't do this too. Only people who have access to this repo, can merge this pull request, such as @temasek

**Comment by temasek** [comment]
I kept rejecting because your simply didn't correct those errors u got. I am not keen in accepting error prone translations.

**Comment by temasek** [comment]
There are quite a number of errors. I will correct those after I merge it.

As I appreciate translation contributions, I would like an error free submission.

**Pull request merged**
