### PR TITLE
Updated czech translation

### PR DESCRIPTION
**Pull request by kecinzer**
Enjoy one of the last commits :)

Signed-off-by: Petr kecinzer Řezníček kecinzer@gmail.com

### CODE REVIEW

**Comment by temasek** [comment]
Sorry pls redo but last? Oh u retiring?

**Comment by kecinzer** [comment]
I will redo today. I sold my 1+1, iPhone 6+ comes to me today :).

**Comment by temasek** [comment]
OMG! No more Android phone for you? My goodness, what a loss to android community! :(

**Comment by pbeeler** [comment]
hmm, thought there would be a good reason to ditch android. But I see no reasoning here ...

**Comment by pbeeler** [comment]
@kecinzer sorry I can't help myself :D
https://www.youtube.com/watch?v=CZGIn9bpALo

**Pull request closed without merging**
