### PR TITLE
Create cr_strings.xml

### PR DESCRIPTION
**Pull request by brunodmjr**
Brazilian Portuguese (pt_BR) translation made for Temasek's unofficial CM11 for GT-i9300

### CODE REVIEW

**Comment by temasek** [comment]
Title should describe what u do

Example

pt_BR: Update translations

**Comment by temasek** [comment]
Also do not translate this as the version keeps changing.



 <string name="temasek_version_default">V5</string>

**Comment by brunodmjr** [comment]
Ok!
Translate this what? The file?

**Comment by brunodmjr** [comment]
Did i translated "v5"? :P If i did, i was not aware. Sorry.

**Pull request merged**
